//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoRest_AplicandoSerti_BT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volumenes
    {
        public short Id { get; set; }
        public int No_Volumen { get; set; }
        public string Titulo { get; set; }
        public int IsActive { get; set; }
        public short Id_Localizacion { get; set; }
    
        public virtual Localizacion Localizacion { get; set; }
    }
}
